name: budayapedia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0' # Menggunakan batas atas untuk versi SDK

dependencies:
  flutter:
    sdk: flutter

  # --- DEPENDENSI FIREBASE UNTUK LOGIN ---
  # Pastikan paket-paket ini sejajar dengan 'flutter:'
  firebase_core: ^4.2.1     # Ganti dengan versi stabil terbaru jika perlu
  firebase_auth: ^6.1.2     # Wajib untuk autentikasi
  google_sign_in: ^6.1.6   # Wajib untuk login Google
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- KONFIGURASI FLUTTER ---
flutter:

  uses-material-design: true

  # --- ASSET (LOGO) ---
  # Pastikan ini sejajar di bawah 'flutter:'
  assets:
  - assets/

  fonts:
  - family: DMSans
    fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Italic.ttf
          style: italic
        - asset: fonts/DMSans-Light.ttf
          weight: 300
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: fonts/DMSans-Thin.ttf
          weight: 100